### ISSUE TITLE
Passing the correlationid header to outgoing requests

### ISSUE THREAD

**Issue by BvdVen** [ekmsystems/serilog-enrichers-correlation-id#34]
To use the correlationId between multiple services I need to send the header to those outgoing requests. What is the 'easiest' way to do this or could this be done automatically?

**Comment by ejcoyle88** [comment]
For us internally we were lucky to have a wrapper around all of our outgoing requests that we could easily add something to. I use the `HttpContextAccessor` to pull the `HttpContext` and then pull the header out of that, and add the header to my outgoing requests.
I keep the name of the header in my `appsettings`, so that there's no magic strings going on and stuff.

Maybe this could be wrapped up in a helper class and made available as part of this library? 

We could move [`GetCorrelationId`](https://github.com/ekmsystems/serilog-enrichers-correlation-id/blob/ef96526a94a4949bae6591a019f2ac4e980feaca/src/Serilog.Enrichers.CorrelationId/Enrichers/CorrelationIdHeaderEnricher.cs#L43) to its own class, and add some helper methods like:
```c#
public static class HeaderHelpers
{
	public const string DefaultHeaderKey = "x-correlation-id";

	public static string GetCorrelationIdHeader(IHttpContextAccessor contextAccessor, string headerKey = DefaultHeaderKey)
	{
		...
	}

	public static string GetCorrelationIdHeader(this IHttpContextAccessor contextAccessor, string headerKey = DefaultHeaderKey)
	{
		GetCorrelationIdHeader(this, headerKey);
	}
}
```

What do you think? @mrstebo any input on this one?

**Comment by lkurzyniec** [comment]
But the question is - should Serilog enricher interact/modify `Request` and/or `Response`? IMHO the answer is NO. Enricher should only take `correlationId` from `Headers` and add such property to log entry. Right now it modifies `Response` by adding `x-correlation-id` header which is IMHO not good.

For me, this package is Serilog enricher and nothing more. There should be a different package to handle your situation - automagically receive and pass `correlationId` to the next service in the chain.

**Comment by BvdVen** [comment]
I agree about that. So the question is how to get the correlation is anywhere in my code? (As already asked in #12 )

**Comment by lkurzyniec** [comment]
You can write a `Middleware` to rewrite `x-correlation-id` from `Request` to `Response`.

But if you would like to get `correlationId` from request and pass it automagically to the next service, you need to create an infrastructure to do so.

**Comment by ejcoyle88** [comment]
I think you're right in that, by default, this package probably shouldn't modify the response to add a header. I do think its a nice convenience though for those who just want to add this in and get going with a correlation id, so maybe a good change would be to make adding the header if one isn't present configurable?

We could merge `WithCorrelationId` and `WithCorrelationIdHeader` into a single function that takes a configuration class and that decides where to load the correlation id from, and if one should be generated if it isn't found.

Then we could add some helper methods to make it easy to do things like:
- Generate a correlation id (Basically just `Guid.NewGuid()` underneath)
- Get the current requests correlation id
  - This would pull the configuration and figure out where to look, rather than having to seperate methods

Does that sound better?
