### ISSUE TITLE
Setting CorrelationID via code

### ISSUE THREAD

**Issue by cloudb0x** [ekmsystems/serilog-enrichers-correlation-id#38]
Is there a way to set the correlation ID via code for the logger ?

I have a message bus which transmits message through the system - I would like to achieve continuity in my logging so would like to set the correlation ID for the current thread when a message is received in another part of the system by some service and all subsequent logs should have that correlation ID so When do troubleshooting I can trace the request throughout the system.

**Comment by lkurzyniec** [comment]
Right now, when your request contains correlation ID in the header, by using `WithCorrelationIdHeader` enricher your log entries will contain the same correlation ID.

But, if you would like to have the same correlation ID in further parts of the distributed system (next services), you need to get this correlation ID from the header of one request and add it to another/next request. It depends on your infrastructure. It could be either add header and make a request via HttpClient or make a request via client package (if such package exists) with supplied correlation ID header.

As far as I know, there is no automatic solution in Serilog for your question, because as I mentioned above, it depends on how you call to next service.

**Comment by cloudb0x** [comment]
I know how to solve this issue via http calls (using header as you mentioned) the issue comes in when the service bus is delivering a message.  I can pass the correlation Id  to the message from service A and set it but how do I set that same correlation Id  on the other end on service B on the logger ?

**Comment by lkurzyniec** [comment]
You can do it by `LogContext.PushProperty()`. More here: https://github.com/serilog/serilog/wiki/Enrichment#the-logcontext

**Comment by lkurzyniec** [comment]
Btw. there is my PR waiting for acceptance with middleware to rewrite correlation ID from request to response (https://github.com/ekmsystems/serilog-enrichers-correlation-id/pull/36).
